### ISSUE TITLE
Index out of bounds in lensing operator

### ISSUE THREAD

**Issue by aymgal** [aymgal/SLITronomy#8]
For certain sets of lens model parameters, such as large projected mass slope (gamma >~ 2.2 for SPEMD) or large shears (e.g. gamma_ext >~ 0.4), the `LensingOperatorInterpol` mapping fails during construction.

The error message is similar to:
```python
IndexError : index 39313 is out of bounds for axis 0 with size 39204
``` 

Typical lens model parameters leading to the issue: 
```python
kwargs_lens: [

   {'theta_E': 1.8, 'gamma': 2.3, 'center_x': 0, 'center_y': 0, 'e1': 0.1, 'e2': -0.2},     
   {'gamma_ext': 0.02, 'psi_ext': 0.5, 'ra_0': 0, 'dec_0': 0}

]
```
with mass profiles `SPEMD` and `SHEAR_GAMMA_PSI`, and an image 99x99 pixels with pixel size 0.08.

@austinpeel you may already be working on this one, but I open an issue so we keep track of this properly.

**Comment by austinpeel** [comment]
Good catch. I'm working on a fix now. This is happening because large parameter values like that can send some of the (ray-traced) lens-plane coordinates outside of the source-plane grid. 

I thought initially this would only happen when using a `minimal_source_plane`, but nope! We just need to find and remove these out-of-bounds indices early.

**Comment by austinpeel** [comment]
Here's an illustration of the problem.
![out_of_bounds](https://user-images.githubusercontent.com/17024310/77057417-35834500-69d4-11ea-87ca-340e0462b706.png)

I've managed to successfully find and remove all points landing outside of the source plane bounds. I've noticed a new problem now, though, where in cases like this, the resulting lensed image has strange features. There is a strange horizontal break, and the whole image is now offset from center.
![lensed_grf](https://user-images.githubusercontent.com/17024310/77057913-fbff0980-69d4-11ea-939f-5c1829d85c6f.png)

**Comment by aymgal** [comment]
Ah I see. So making the source plane bigger would do the trick. The question would be to find a suitable size automatically.

For the strange feature, do you see it if you simulate the lens analytically ? But indeed, removing those pixels may not be a good solution in the end, because their absence is translated in image plane...

**Comment by austinpeel** [comment]
I used the same lens model (SPEMD + SHEAR_GAMMA_PSI) that you did above, just with a more extreme `gamma_ext`=0.2.

Yeah the lensing offset issue is coming from removing at the very start all of the betas that fall outside of the source plane grid. There should be a way to keep them in the calculation though--e.g. by temporarily expanding the source plane, as you say--and then just shrinking it back to size at the end.

**Comment by aymgal** [comment]
Ok so a simple way to go is to compute the coordinates of the most extreme points in source plane, and define the grid size such that these points are in. With your algorithm it is less of an issue to have huge grid sizes, and this should not happen too much because these extreme profiles are not common at all.

**Comment by austinpeel** [comment]
Aha, there was an easier fix ! For `rows`, I just needed to make sure to use the original index positions of the `betas` for the ones that survive the cut. Just a change in one line of code :)
![lensed_grf_fixed](https://user-images.githubusercontent.com/17024310/77073183-23fb6680-69ef-11ea-9cc6-17f99e4206f3.png)

**Comment by herjy** [comment]
So now do you remove those pixels? I would generally argue against it and expand the source plane instead.

**Comment by austinpeel** [comment]
For now I'm just removing them. I agree expanding the source plane would be better. In most normal cases, only a handful (if any) will need to be removed, and this should only cause some slight inaccuracies on parts of the edges of the lensed image.

**Comment by herjy** [comment]
Unless there is a neighbouring source at these locations.
